// <auto-generated />
using System;
using InvestmentPortfolioManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentPortfolioManager.Data.Migrations
{
    [DbContext(typeof(InvestmentPortfolioDbContext))]
    [Migration("20260117131206_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.Asset", b =>
                {
                    b.Property<Guid>("Asset_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<double>("CurrentPrice")
                        .HasColumnType("float");

                    b.Property<Guid>("InvestmentPortfolioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("LowPriceThreshold")
                        .HasColumnType("float");

                    b.Property<double>("MeanReturn")
                        .HasColumnType("float");

                    b.Property<double>("PurchasePrice")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("Volatility")
                        .HasColumnType("float");

                    b.HasKey("Asset_id");

                    b.HasIndex("InvestmentPortfolioId");

                    b.ToTable("Assets");

                    b.HasDiscriminator<string>("AssetType").HasValue("Asset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.InvestmentPortfolio", b =>
                {
                    b.Property<Guid>("InvestmentPortfolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestmentPortfolioId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.Bond", b =>
                {
                    b.HasBaseType("InvestmentPortfolioManager.Core.Models.Asset");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Bond");
                });

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.Commodity", b =>
                {
                    b.HasBaseType("InvestmentPortfolioManager.Core.Models.Asset");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Commodity");
                });

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.Cryptocurrency", b =>
                {
                    b.HasBaseType("InvestmentPortfolioManager.Core.Models.Asset");

                    b.HasDiscriminator().HasValue("Cryptocurrency");
                });

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.RealEstate", b =>
                {
                    b.HasBaseType("InvestmentPortfolioManager.Core.Models.Asset");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("RealEstate");
                });

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.Stock", b =>
                {
                    b.HasBaseType("InvestmentPortfolioManager.Core.Models.Asset");

                    b.HasDiscriminator().HasValue("Stock");
                });

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.Asset", b =>
                {
                    b.HasOne("InvestmentPortfolioManager.Core.Models.InvestmentPortfolio", "InvestmentPortfolio")
                        .WithMany("Assets")
                        .HasForeignKey("InvestmentPortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestmentPortfolio");
                });

            modelBuilder.Entity("InvestmentPortfolioManager.Core.Models.InvestmentPortfolio", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
